name: picture_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_cropper: ^1.4.1
  image_picker: 0.8.4+2
  path_provider: ^2.0.5
  pedantic_mono: ^1.14.0+1

flutter:
  uses-material-design: true
